---
title: "1InitialiseDirectories"
author: "Dave Lovell"
date: "20/02/2020"
output: html_document
---

```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries1, message = FALSE, warning = FALSE}
# Libraries ---------
require("here")
```

We are here: `r here()`

A note about `here()`: It's very useful for working out the functional root of a project or repo. We can use `dr_here()` to get the reasoning for why `here()` returns what it does:

```{r showHere}
dr_here()
```

## Create directory structure (things not pushed to git)

```{r structureCreate}
!if("data" %in% dir(here())) dir.create("data")
```

## Look for excel files

```{r excelFilePlaces}
allFilesThere <- TRUE
### Is there a (correctly named) Portsmouth-2018 file (in the right place) --------------------
ifelse(file.exists(here("data/portsmouthLeaders2018.xlsx")),
       "Portsmouth 2018 File Found :)",
       {allFilesThere <- FALSE
         "Portsmouth 2018 File not Found: Please place 'portsmouthLeaders2018.xlsx' in the 'data' directory and knit this document again"})

### Is there a (correctly named) Portsmouth-2019 file (in the right place) --------------------
ifelse(file.exists(here("data/portsmouthLeaders2019.xlsx")),
       "Portsmouth 2019 File Found :)",
       {allFilesThere <- FALSE
         "Portsmouth 2019 File not Found: Please place 'portsmouthLeaders2019.xlsx' in the 'data' directory and knit this document again"})
```

## save Progress Rdat
```{r progressRdat}
saveRDS(allFilesThere, here("data/progressRdats/1.rdat"))
readRDS(here("data/progressRdats/1.rdat"))
```

