---
title: "checkData"
author: "Dave Lovell"
date: "20/02/2020"
output:
  html_document:
    code_folding: hide
---

```{r setup2, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries2}
require("here")
```

## Check the data exists

```{r excelFilePlaces}
allFilesThere <- TRUE


### Filename vars -----------------------------------------------------------------------------
lookFileDir <- "O:\\WCC\\Learning and Development\\Research\\PROJECT - Portsmouth 2019 onwards\\Data\\unclean"
          file18 <- paste(lookFileDir, "portsmouthLeaders2018.xlsx", sep = "\\")
          file19 <- paste(lookFileDir, "portsmouthLeaders2019.xlsx", sep = "\\")
          attenders18 <- paste(lookFileDir, "attenders2018Unclean.csv", sep = "\\")

### Is there a (correctly named) Portsmouth-2018 file (in the right place) --------------------
ifelse(file.exists(here("data/portsmouthLeaders2018.xlsx")),
       "Portsmouth 2018 File Found :)",
       {
         # If file exists on O drive
         if(file.exists(file18)){
           # Copy file from O Drive
           file.copy(from = file18,
                     to = here("data"))
           "Portsmouth 2018 succesfully copied from O drive"
         } else {
         allFilesThere <- FALSE
       "Portsmouth 2018 File not found and O:// drive not available: Please place 'portsmouthLeaders2018.xlsx' in the 'data' directory and knit this document again"}})
          

### Is there a (correctly named) Portsmouth-2019 file (in the right place) --------------------
ifelse(file.exists(here("data/portsmouthLeaders2019.xlsx")),
       "Portsmouth 2019 File Found :)",
       {
         # If file exists on O drive
         if(file.exists(file19)){
           # Copy file from O Drive
           file.copy(from = file19,
                     to = here("data"))
           "Portsmouth 2019 succesfully copied from O drive"
         } else {
         allFilesThere <- FALSE
       "Portsmouth 2019 File not found and O:// drive not available: Please place 'portsmouthLeaders2019.xlsx' in the 'data' directory and knit this document again"}})

### Is there a (correctly named) Attenders 2018 file (in the right place) --------------------
ifelse(file.exists(here("data/attenders2018Unclean.csv")),
       "Attenders 2018 File Found :)",
       {
         # If file exists on O drive
         if(file.exists(attenders18)){
           # Copy file from O Drive
           file.copy(from = attenders18,
                     to = here("data"))
           "Attenders 2018 succesfully copied from O drive"
         } else {
         allFilesThere <- FALSE
       "Attenders 2018 file not found and O:// drive not available: Please place 'attenders2018Unlean.csv' in the 'data' directory and knit this document again"}})
```

```{r writeRDS2}
saveRDS(allFilesThere, here("data/progressRdats/2.rdat"))
readRDS(here("data/progressRdats/2.rdat"))
```


