---
title: "4cleanData"
author: "Dave Lovell"
date: "24/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries4, message = FALSE, warning = FALSE}
require("here")
require("dplyr")
require("magrittr")
require("tidyr")
```
## Clean the Data

Make it real good yeah.


### Read the unclean data

```{r readUnclean}
responses <- 
  readRDS(here("data/generalRdats/leaderResponsesUnclean.rdat"))

nrow(responses)
ncol(responses)
```

### Rename the columns

#### Catch old names

```{r catchNames}
oldNames <- names(responses)
```

NB put the below together with `paste0(" = \"", names(responses),"\", ") %>% writeClipboard`

#### Rename
```{r renameCols}
responses %<>%
  rename("info_stillMeeting" = "info_Is this fresh expression/church plant still meeting?", 
"fxc" = "fxc", 
"info_deanery" = "info_Deanery", 
"info_sendingChurch" = "info_Name of Sending Church", 
"info_venueDetails" = "info_Normal meeting place name, address and website (if any)", 
"info_startDate" = "info_Start", 
"info_newFurther" = "info_New and further group?", 
"info_anglican" = "info_Anglican or Anglican partner?", 
"info_howMissional" = "info_Describe how you tried to engage with non-church goers", 
"info_isChurch" = "info_Church in its own right?", 
"info_frequency" = "info_How often do you meet?", 
"info_days" = "info_Which day (s)", 
"info_startTime" = "info_Start time", 
"info_endTime" = "info_End time", 
"info_description" = "info_Please describe your fxC", 
"info_relativeLocation" = "info_WHERE is the fresh expression planted in relation to the “sending” church? Tick only one box", 
"mot_bishopOrDiocesan" = "mot_Bishop / diocesan initiative", 
"mot_churchShouldGrow" = "mot_Grow is what Church should do", 
"mot_inadequatePenetration" = "mot_Inadequate penetration of the parish", 
"mot_newHousing" = "mot_New housing opportunity", 
"mot_physicallyRestricted" = "mot_Physically restricted at sending church", 
"mot_increaseDiversity" = "mot_Provide increased diversity", 
"mot_unreachedGroup" = "mot_Unreached people group", 
"mot_Other" = "mot_Other", 
"mot_otherDetail" = "mot_...10", 
"lead_name" = "lead_Name of leader", 
"lead_address" = "lead_Address", 
"lead_email" = "lead_Email address", 
"lead_phone" = "lead_Phone number", 
"lead_teamSize" = "lead_Number of people on leadership team", 
"lead_office" = "lead_Office", 
"lead_payStatus" = "lead_Pay Status", 
"lead_time" = "lead_Time", 
"lead_gender" = "lead_Gender", 
"train_msm" = "lead_Mission shaped ministry", 
"train_msi" = "lead_Mission shaped introductions", 
"train_plantingModule" = "lead_Planting module", 
"train_trainingEvent" = "lead_Training event", 
"train_consultancy" = "lead_Consultancy provided", 
"train_fxcExperience" = "lead_Previous fresh expression experience", 
"train_non" = "lead_None", 
"train_other" = "lead_Other", 
"num_sentAdults" = "num_Number of adults sent to begin FxC", 
"num_sentChildren" = "num_Number of children sent to begin FxC", 
"num_averageAdults" = "num_Average attendance adults", 
"num_averageChildren" = "num_Average attendance children", 
"num_averageAttendance" = "num_Total average attendance", 
"num_wc" = "num_Total Fresh Expression worshipping community (all people who would consider themselves part of the fresh expression)", 
"num_volunteers" = "num_Estimated number of members actively volunteering for the Fresh Expression",
"trad_angloCatholic" = "trad_Anglo-Catholic", 
"trad_central" = "trad_Central", 
"trad_charismatic" = "trad_Charismatic", 
"trad_evangelical" = "trad_Evangelical", 
"trad_liberal" = "trad_Liberal", 
"df_denominationalFeatures" = "trad_Denominal features", 
"bui_type" = "trad_Ecclesical / Secular / House", 
"bui_ownership" = "trad_Owned / Rented / Loaned", 
"bui_license" = "trad_Licensed for public worship / Unlicensed", 
"bui_variety" = "trad_Variety of locations used?", 
"bui_legalStatus" = "trad_What legal status?", 
"desc_allAge" = "desc_All age worship", 
"desc_alternative" = "desc_Alternative worship", 
"desc_cafe" = "desc_Café Church", 
"desc_cell" = "desc_Cell Church", 
"desc_childFocused" = "desc_Child Focused Church", 
"desc_underFives" = "desc_Church based on <5s", 
"desc_cluster" = "desc_Cluster based Church", 
"desc_cdp" = "desc_Communiuty Development Plant", 
"desc_messy" = "desc_Messy Church", 
"desc_midweek" = "desc_Midweek Chuch", 
"desc_multipleSunday" = "desc_Multiple Sunday congeration", 
"desc_network" = "desc_Network Church", 
"desc_newMonastic" = "desc_New Monastic", 
"desc_olderPeople" = "desc_Older People's Church", 
"desc_schoolBased" = "desc_School based Church", 
"desc_seeker" = "desc_Seeker Church", 
"desc_tradPlant" = "desc_Traditional Church Plant", 
"desc_newTradService" = "desc_New Traditional service", 
"desc_youthChurch" = "desc_Youth Church", 
"desc_other" = "desc_Other", 
"desc_otherDetail" = "desc_Special Interest group: e.g. Arts/Goths/workplace/helping addicts/learning disability. Describe it", 
"geog_expandedVillage" = "geog_Expanded village", 
"geog_rural" = "geog_Rural", 
"geog_localAuthorityEstate" = "geog_Local authority estate", 
"geog_privateEstate" = "geog_Private estate", 
"geog_suburb" = "geog_Suburb", 
"geog_town" = "geog_Town", 
"geog_cityCentre" = "geog_City centre", 
"geog_localAndPrivateEstate" = "geog_Local and private estate", 
"geog_urban" = "geog_Urban", 
"geog_urbanPriorityArea" = "geog_Urban priority area", 
"geog_newTown" = "geog_New town", 
"geog_other" = "geog_Other", 
"dive_typicality" = "geog_How typical are the people in your Fresh Expression of the social area(s)/context?", 
"dive_diversity" = "geog_How ethnically diverse is your fresh Expression?", 
"netNei_taskNeighbourhood" = "mis_Mission task neighbourhood", 
"netNei_taskNetwork" = "mis_Mission task network", 
"netNei_resultNeighbourhood" = "mis_Result through neighbourhood", 
"netNei_resultNetwork" = "mis_Result through network", 
"mis_taskChr" = "mis_Mission task - Christians", 
"mis_taskDe" = "mis_Mission task - de-churched", 
"mis_taskNon" = "mis_Mission task - non-churched", 
"mis_chr" = "mis_Christians %", 
"mis_de" = "mis_De-churched %", 
"mis_non" = "mis_Non-churched %", 
"pp_pioneer" = "mis_Pioneer work", 
"pp_progression" = "mis_Progression", 
"mis_dynamic" = "mis_Mission support dynamic", 
"bib_sermonTalk" = "bib_Sermon/Talk", 
"bib_passages" = "bib_Passages read in public", 
"bib_groupStudy" = "bib_Study in groups", 
"bib_atHome" = "bib_Encourage individual reading at home", 
"bib_memoryVerses" = "bib_Memory verses", 
"bib_storyTelling" = "bib_Story telling", 
"bib_creative" = "bib_Creative activity / resource", 
"bib_other" = "bib_Other", 
"bib_notAtThisStage" = "bib_Not at this stage yet", 
"wor_worshipBand" = "wc_Worship band", 
"wor_congregationalSinging" = "wc_Congregational singing", 
"wor_artDramaPoetry" = "wc_Art / Drama / Poetry", 
"wc_musically" = "wc_Musically", 
"wor_openPrayer" = "wc_Open Prayer", 
"wor_bibleReading" = "wc_Bible reading", 
"wor_sermon" = "wc_A sermon or talk", 
"wor_intercessions" = "wc_Intercessions", 
"wor_healing" = "wc_Healing ministry", 
"wor_communion" = "wc_Communion", 
"wor_craft" = "wc_Craft activities", 
"wor_food" = "wc_Sharing food", 
"wor_actsKindness" = "wc_Acts of kindness and generosity", 
"wor_blessings" = "wc_Blessings", 
"wor_practiseDisciples" = "wc_Practice as disciples in the community", 
"wor_storiesGodAtWork" = "wc_Telling stories of God at work in lives", 
"wor_silence" = "wc_Silence", 
"wor_other" = "wc_Other...19", 
"wor_otherDetail" = "wc_...20", 
"com_spaceToChat" = "wc_Space and time to chat", 
"com_refreshements" = "wc_Offer refreshments", 
"com_hospitatlity" = "wc_Good hospitality", 
"com_socialMedia" = "wc_Social media", 
"com_activeWebsite" = "wc_An active website", 
"com_specialEvents" = "wc_Special events", 
"com_meal" = "wc_Share in a meal", 
"com_socialActivities" = "wc_Social activities", 
"com_socialAction" = "wc_Social action projects", 
"com_notYet" = "wc_Not yet", 
"comOther" = "wc_Other...31", 
"sac_communion" = "sac_Communion services?", 
"sac_communionFrequency" = "sac_If yes how frequently? (communion)", 
"sac_agape" = "sac_Agape?", 
"sac_baptisms" = "sac_Baptisms?", 
"sac_adultBaptisms" = "sac_If yes number of adults (baptism)", 
"sac_childBaptisms" = "sac_If yes number of children (baptism)", 
"sac_confirmations" = "sac_Confirmations?", 
"sac_adultConfirmations" = "sac_If yes number of adults (confirmation)", 
"sac_childConfirmations" = "sac_If yes number of children (confirmation)", 
"sac_whyNotCommunnion" = "sac_If no why? - Communion", 
"sac_whyNotBaptisms" = "sac_If no why? - Baptism", 
"sac_whyNotConfirmations" = "sac_If no why? Confirmation", 
"sac_whoPresidesCommunion" = "sac_If yes who presides? - Communion", 
"sac_whoPresidesBaptism" = "sac_If yes who presides? - Baptism", 
"ts_finacing" = "ts_Self-financing", 
"ts_governing" = "ts_Self-governing", 
"ts_reproducing" = "ts_Self-reproducing", 
"ts_notAtThisStage" = "ts_Not at this stage yet", 
"sf_collections" = "ts_Collections / Donations", 
"sf_regualar" = "ts_Regular giving / standing orders", 
"sf_coverRunning" = "ts_Cover running costs", 
"sf_coverAllCosts" = "ts_Cover all costs (inc. staff)", 
"sf_intentionOnly" = "ts_Intention Only", 
"sf_other" = "ts_Other (self financing)", 
"sg_leadershipTeam" = "ts_Leadership team", 
"sg_legalStructure" = "ts_Formal legal structure", 
"sg_informalPcc" = "ts_Informal PCC representation", 
"sg_formalPcc" = "ts_Formal PCC representation", 
"sg_intentionOnly" = "ts_Intention only...16", 
"sg_other" = "ts_Other (self-governing)", 
"sr_indigenousLeaders" = "ts_Indigenous leaders", 
"sr_enabledElsewhere" = "ts_Enabled reproduction elsewhere", 
"sr_furtherFxc" = "ts_Started further fresh expressions", 
"sr_furtherOutreach" = "ts_Started further outreach", 
"sr_ordinand" = "ts_Ordinand", 
"sr_newBelievers" = "ts_New believers", 
"sr_virtuousLives" = "ts_More virtuous lives", 
"sr_intentionOnly" = "ts_Intention only...25", 
"sr_other" = "ts_Other (self-reproducing)", 
"sr_otherDetail" = "ts_...27", 
"ste_financialResponsibility" = "ste_Which is responsible for the finance of the fxC?", 
"ste_incomeStreams" = "ste_What are the current income streams that enable the Fresh Expression to fund its activities & how much was received through each element during  the last financial year (Jan –Dec )?", 
"ste_surplus" = "ste_What was the level of surplus or deficit for the Fresh Expression in the last financial year?", 
"ste_givers" = "ste_How many people contribute financially to the Fresh Expression?", 
"ste_plannedGivers" = "ste_Of those people detailed at point 3, how many are planned givers (ie in a committed way each week/month to the fresh expression)", 
"ste_fxcExclusively" = "ste_Of those planned givers, how many are only giving to the fresh expression and how many are existing parish planned givers?", 
"ste_supportFromCongregation" = "ste_How much financial support is there from  the main congregation members?", 
"ste_opportunitiesCommunicate" = "ste_The intended message is that people can participate at no cost while there being opportunities to give.  What opportunities are there to give and how are these communicated?", 
"ste_howBuildStewardship" = "ste_What steps have been taken already to build in stewardship principles in terms of time, talents and money into the fresh expression activities?", 
"ste_plansSustainibility" = "ste_What plans and strategy is there to ensure financial sustainability over the next 2-3 years and 3-5 years?", 
"ste_responsibleDecisions" = "ste_Which is responsible for the decision-making and reporting of the fxC?", 
"dis_smallGroups" = "de_Small groups", 
"dis_oneToOne" = "de_One-to-one", 
"dis_courses" = "de_Running courses", 
"dis_serving" = "de_Serving in teams", 
"dis_notAtThisStage" = "de_Not at this stage yet (discipleship)", 
"dis_other" = "de_Other (discipleship)", 
"eva_course" = "de_Enquirers course", 
"eva_relationships" = "de_Building relationships with others", 
"eva_membersShareStories" = "de_Members share their story", 
"eva_inviteWorship" = "de_Inviting to worship", 
"eva_inviteEvents" = "de_Inviting to events", 
"eva_service" = "de_Acts of service", 
"eva_notAtThisStage" = "de_Not at this stage yet (evangelism)", 
"eva_other" = "de_Other (evangelism)", 
"tranche" = "tranche", 
"lead_name2" = "lead_Name of leader 2", 
"lead_email2" = "lead_Email address 2", 
"lead_phone2" = "lead_Phone number 2", 
"lead_name3" = "lead_Name of leader 3", 
"lead_email3" = "lead_Email address 3", 
"lead_phone3" = "lead_Phone number 3")
```

### Document names

```{r nameDocument}
saveRDS(tibble(oldNames,
               names(responses)),
        here("data/generalRdats/names.rdat"))
```

## Assign variable types


### Logicals

Are these fields all safe to interpret as logicals?

```{r findLogicals}
responses %>% 
  mutate_all(as.character) %>% 
  select(contains("mot_"),
         contains("train_"),
         contains("trad_"),
         contains("desc_"),
         contains("geog_"),
         contains("bib_"),
         contains("wor_"),
         contains("com_"),
         contains("ts_"),
         contains("sf_"),
         contains("sg_"),
         contains("sr_"),
         contains("dis_"),
         contains("eva_"),
         -contains("other"),
         -contains("notAtThisStage")) %>% 
  pivot_longer(everything()) %>% 
  pull(value) %>% 
  unique 
```
These fields can all be interpreted as logicals with `!is.na(x)`.

```{r makeLogicals}
responses %<>% 
  mutate_at(vars(contains("mot_"),
         contains("train_"),
         contains("trad_"),
         contains("desc_"),
         contains("geog_"),
         contains("bib_"),
         contains("wor_"),
         contains("com_"),
         contains("ts_"),
         contains("sf_"),
         contains("sg_"),
         contains("sr_"),
         contains("dis_"),
         contains("eva_"),
         -contains("other"),
         -contains("notAtThisStage")),
         ~ !is.na(.))
```

