---
title: "readExcels"
author: "Dave Lovell"
date: "21/02/2020"
output: html_document
---

```{r setup3, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries3, message = FALSE}
library("here")
library("readxl")
library("dplyr")
library("purrr")
library("magrittr")
```

## Create tibble with sheet names and data selections

```{r excelSheet}
excelSheet <- 
  tibble(sheetNames = c("basic info", "motivations", "leadership", "numbers",
                        "tradition", "description", "geography", "mission", 
                        "engage with bible", "worship community", "sacraments",
                        "three self", "stewardship", "disciple evangelism")) %>%
  mutate(skipRows = sheetNames %in% c("motivations", "tradition",
                                      "worship community", "three self",
                                      "disciple evangelism") %>% 
           as.numeric)

excelSheet
```

## Do a two 'readxl's for each row

```{r readExcels, warning = FALSE}

excelSheet %<>%
  mutate(
    data2018 = map2(sheetNames, skipRows,
                    ~ {read_excel(
                       here("data/portsmouthLeaders2018.xlsx"),
                       sheet = .x,
                       skip = .y)}),
    data2019 = map2(sheetNames, skipRows,
                    ~ {read_excel(
                       here("data/portsmouthLeaders2019.xlsx"),
                       sheet = .x,
                       skip = .y)}))

excelSheet
```

## Dimension investigation

Which of these tibbles have inconsitent dimensions between years?

```{r lookDims}
filter(excelSheet, sapply(data2018,ncol) != sapply(data2019,ncol))
```

Only 'sacraments' and 'leadership' (hopefully!). These are the sections in which questions were added between 2018 and 2019. 

## Names investigation

```{r namesLook}
excelSheet %>% 
  mutate(badnames = map2(data2018, data2019, 
                        ~ {
                          c(names(.x)[!(names(.x) %in% intersect(names(.x),names(.y)))],
                            names(.y)[!(names(.y) %in% intersect(names(.x),names(.y)))])
                        })) %>% 
  filter(sapply(badnames,length) > 1) %>% 
  select(sheetNames, badnames) %>% 
  mutate(what = sapply(badnames,toString)) %T>%
  {pull(., badnames) %>% 
      sapply(print)}
```
